package compilador.pacman;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 25 23:04:10 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLADOBLE = 43;
  public static final int NUMERO = 46;
  public static final int DOSPUNTOS = 31;
  public static final int BRADER = 22;
  public static final int FUNCTION = 39;
  public static final int MULT = 13;
  public static final int CHAR = 5;
  public static final int SIMBOLO = 45;
  public static final int CASE = 11;
  public static final int RESTA = 15;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 17;
  public static final int FOR = 7;
  public static final int NOIGUAL = 30;
  public static final int MENORIGUAL = 27;
  public static final int IGUAL = 29;
  public static final int BOOL = 3;
  public static final int DIV = 16;
  public static final int SUMA = 14;
  public static final int IF = 9;
  public static final int LLAIZQ = 23;
  public static final int MAYORIGUAL = 28;
  public static final int EOF = 0;
  public static final int PARIZQ = 19;
  public static final int RETURN = 41;
  public static final int ASIG = 12;
  public static final int TRUE = 36;
  public static final int COMILLA = 42;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int NULL = 38;
  public static final int MENOR = 25;
  public static final int BRAIZQ = 21;
  public static final int BREAK = 33;
  public static final int IDENT = 34;
  public static final int VOID = 40;
  public static final int STRINGVAL = 44;
  public static final int SWITCH = 10;
  public static final int MAYOR = 26;
  public static final int ELSE = 35;
  public static final int PUNTO = 32;
  public static final int WHILE = 8;
  public static final int FLOAT = 4;
  public static final int STRING = 6;
  public static final int LLADER = 24;
  public static final int FALSE = 37;
  public static final int PARDER = 20;
}

