/* The following code was generated by JFlex 1.4.3 on 3/15/13 7:50 PM */


import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/15/13 7:50 PM from the specification file
 * <tt>/Users/mariomaradiaga/Documents/Projects/Compilador---PACMAN/src/LexerPacMan.jflex</tt>
 */
class LexerPacMan implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\10\1\0\1\13\1\7\22\0\1\11\1\56\1\14"+
    "\3\0\1\60\1\15\1\40\1\41\1\46\1\47\1\45\1\50\1\4"+
    "\1\51\12\2\1\44\1\52\1\54\1\55\1\53\2\0\32\1\1\42"+
    "\1\16\1\43\1\0\1\3\1\0\1\23\1\17\1\22\1\24\1\31"+
    "\1\32\2\1\1\20\2\1\1\34\1\35\1\21\1\26\1\36\1\1"+
    "\1\30\1\25\1\33\1\27\1\37\4\1\1\5\1\57\1\6\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\3\7"+
    "\1\10\1\11\13\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\2\1\1\31\1\32\1\33\4\0\1\34"+
    "\6\2\1\35\7\2\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\11\51\1\52"+
    "\1\53\2\2\1\54\1\2\1\55\1\56\2\2\1\57"+
    "\2\2\1\60\5\2\1\61\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\2\1\74"+
    "\13\2\1\75\10\2\1\76\1\2\1\77\1\100\1\2"+
    "\1\101\2\2\1\102\1\103\1\2\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\223\0\u0126"+
    "\0\223\0\u0157\0\223\0\u0188\0\223\0\223\0\u01b9\0\u01ea"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\223\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\u03d4\0\223\0\223\0\u0405\0\u0436\0\223\0\u0467"+
    "\0\u0498\0\u04c9\0\u04fa\0\223\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\u0126\0\223\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c"+
    "\0\223\0\223\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\223\0\223\0\u089d\0\u08ce\0\u08ff\0\u0930"+
    "\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u05be\0\304\0\u0a25\0\u0a56"+
    "\0\304\0\u0a87\0\304\0\304\0\u0ab8\0\u0ae9\0\304\0\u0b1a"+
    "\0\u0b4b\0\304\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\223"+
    "\0\223\0\223\0\223\0\223\0\223\0\223\0\223\0\304"+
    "\0\304\0\304\0\u0c71\0\304\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\304"+
    "\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014"+
    "\0\304\0\u1045\0\304\0\304\0\u1076\0\304\0\u10a7\0\u10d8"+
    "\0\304\0\304\0\u1109\0\304";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\7\1\10\1\11\1\12"+
    "\2\13\1\14\1\4\1\15\1\16\1\4\1\17\1\5"+
    "\1\20\1\21\1\5\1\22\1\23\2\5\1\24\1\25"+
    "\1\26\2\5\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\7\53\2\0"+
    "\3\53\1\54\1\53\1\55\42\53\7\56\2\0\4\56"+
    "\1\0\1\57\42\56\62\0\3\5\13\0\21\5\23\0"+
    "\1\6\1\0\1\60\54\0\6\61\1\62\52\61\10\0"+
    "\1\13\63\0\1\13\46\0\3\5\13\0\1\5\1\63"+
    "\17\5\22\0\3\5\13\0\4\5\1\64\3\5\1\65"+
    "\10\5\22\0\3\5\13\0\4\5\1\66\3\5\1\67"+
    "\10\5\22\0\3\5\13\0\12\5\1\70\6\5\22\0"+
    "\3\5\13\0\1\5\1\71\17\5\22\0\3\5\13\0"+
    "\12\5\1\72\6\5\22\0\3\5\13\0\2\5\1\73"+
    "\16\5\22\0\3\5\13\0\1\5\1\74\2\5\1\75"+
    "\14\5\22\0\3\5\13\0\1\5\1\76\17\5\22\0"+
    "\3\5\13\0\4\5\1\77\14\5\22\0\3\5\13\0"+
    "\12\5\1\100\6\5\74\0\1\101\62\0\1\102\60\0"+
    "\1\103\60\0\1\104\62\0\1\105\61\0\1\106\7\53"+
    "\2\0\3\53\1\0\1\53\1\0\42\53\14\0\1\107"+
    "\4\0\1\110\6\0\1\111\2\0\1\112\42\0\1\113"+
    "\43\0\10\114\1\0\3\114\1\115\1\116\1\117\1\120"+
    "\1\114\1\121\6\114\1\122\1\114\1\123\1\124\25\114"+
    "\2\0\1\125\57\0\3\5\13\0\2\5\1\126\16\5"+
    "\22\0\3\5\13\0\5\5\1\127\13\5\22\0\3\5"+
    "\13\0\15\5\1\130\3\5\22\0\3\5\13\0\5\5"+
    "\1\131\1\132\12\5\22\0\3\5\13\0\11\5\1\133"+
    "\7\5\22\0\3\5\13\0\3\5\1\134\7\5\1\135"+
    "\5\5\22\0\3\5\13\0\2\5\1\136\13\5\1\137"+
    "\2\5\22\0\3\5\13\0\14\5\1\140\4\5\22\0"+
    "\3\5\13\0\3\5\1\141\10\5\1\142\4\5\22\0"+
    "\3\5\13\0\2\5\1\143\16\5\22\0\3\5\13\0"+
    "\15\5\1\144\3\5\22\0\3\5\13\0\12\5\1\145"+
    "\6\5\22\0\3\5\13\0\3\5\1\146\15\5\22\0"+
    "\3\5\13\0\11\5\1\147\7\5\36\0\1\150\60\0"+
    "\1\151\60\0\1\152\60\0\1\153\60\0\1\154\60\0"+
    "\1\155\60\0\1\156\60\0\1\157\44\0\3\5\13\0"+
    "\4\5\1\160\14\5\22\0\3\5\13\0\7\5\1\161"+
    "\11\5\22\0\3\5\13\0\7\5\1\162\11\5\22\0"+
    "\3\5\13\0\12\5\1\163\6\5\22\0\3\5\13\0"+
    "\7\5\1\164\11\5\22\0\3\5\13\0\7\5\1\165"+
    "\11\5\22\0\3\5\13\0\4\5\1\166\14\5\22\0"+
    "\3\5\13\0\3\5\1\167\15\5\22\0\3\5\13\0"+
    "\6\5\1\170\12\5\22\0\3\5\13\0\2\5\1\171"+
    "\16\5\22\0\3\5\13\0\16\5\1\172\2\5\22\0"+
    "\3\5\13\0\5\5\1\173\13\5\22\0\3\5\13\0"+
    "\3\5\1\174\15\5\22\0\3\5\13\0\11\5\1\175"+
    "\7\5\22\0\3\5\13\0\6\5\1\176\12\5\22\0"+
    "\3\5\13\0\4\5\1\177\14\5\22\0\3\5\13\0"+
    "\7\5\1\200\11\5\22\0\3\5\13\0\14\5\1\201"+
    "\4\5\22\0\3\5\13\0\4\5\1\202\14\5\22\0"+
    "\3\5\13\0\4\5\1\203\14\5\22\0\3\5\13\0"+
    "\14\5\1\204\4\5\22\0\3\5\13\0\2\5\1\205"+
    "\16\5\22\0\3\5\13\0\7\5\1\206\11\5\22\0"+
    "\3\5\13\0\6\5\1\207\12\5\22\0\3\5\13\0"+
    "\11\5\1\210\7\5\22\0\3\5\13\0\2\5\1\211"+
    "\16\5\22\0\3\5\13\0\5\5\1\212\13\5\22\0"+
    "\3\5\13\0\7\5\1\213\11\5\22\0\3\5\13\0"+
    "\7\5\1\214\11\5\22\0\3\5\13\0\5\5\1\215"+
    "\13\5\22\0\3\5\13\0\7\5\1\216\11\5\22\0"+
    "\3\5\13\0\4\5\1\217\14\5\22\0\3\5\13\0"+
    "\12\5\1\220\6\5\22\0\3\5\13\0\12\5\1\221"+
    "\6\5\22\0\3\5\13\0\6\5\1\222\12\5\22\0"+
    "\3\5\13\0\11\5\1\223\7\5\22\0\3\5\13\0"+
    "\7\5\1\224\11\5\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4410];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\2\11\13\1\10\11\1\1\2\11\2\1\1\11"+
    "\4\1\1\11\1\1\4\0\1\11\16\1\14\11\33\1"+
    "\10\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

StringBuffer string = new StringBuffer();

/**
 * Retorna un nuevo Symbol con el id del token y la columna y 
 * fila del mismo.
 */
Symbol nuevoSymbol(int tokenId) {
    return new java_cup.runtime.Symbol(tokenId, yyline, yycolumn);
}

/**
 * Retorna un nuevo Symbol con el id del token, la columna y 
 * fila del mismo y su valor. El valor es usado para tokens como
 * identificadores y números.
 */
Symbol nuevoSymbol(int tokenId, Object valor) {
    return new java_cup.runtime.Symbol(tokenId, yyline, yycolumn, valor);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerPacMan(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerPacMan(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return nuevoSymbol(sym.COMA);
          }
        case 69: break;
        case 47: 
          { return nuevoSymbol(sym.CHAR);
          }
        case 70: break;
        case 43: 
          { return nuevoSymbol(sym.BOOL);
          }
        case 71: break;
        case 12: 
          { return nuevoSymbol(sym.BRAIZQ);
          }
        case 72: break;
        case 56: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\t'));
          }
        case 73: break;
        case 66: 
          { return nuevoSymbol(sym.SWITCH);
          }
        case 74: break;
        case 20: 
          { return nuevoSymbol(sym.PUNTOCOMA);
          }
        case 75: break;
        case 32: 
          { return nuevoSymbol(sym.MENORIGUAL);
          }
        case 76: break;
        case 50: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\''));
          }
        case 77: break;
        case 33: 
          { return nuevoSymbol(sym.NOIGUAL);
          }
        case 78: break;
        case 39: 
          { string.append('\t');
          }
        case 79: break;
        case 48: 
          { return nuevoSymbol(sym.INT);
          }
        case 80: break;
        case 61: 
          { return nuevoSymbol(sym.FALSE);
          }
        case 81: break;
        case 35: 
          { return nuevoSymbol(sym.AND);
          }
        case 82: break;
        case 24: 
          { return nuevoSymbol(sym.NOT);
          }
        case 83: break;
        case 18: 
          { return nuevoSymbol(sym.RESTA);
          }
        case 84: break;
        case 4: 
          { return nuevoSymbol(sym.PUNTO);
          }
        case 85: break;
        case 19: 
          { return nuevoSymbol(sym.DIV);
          }
        case 86: break;
        case 27: 
          { string.append('\\');
          }
        case 87: break;
        case 38: 
          { string.append('\r');
          }
        case 88: break;
        case 7: 
          { /* Ignorar todos los espacios*/
          }
        case 89: break;
        case 58: 
          { return nuevoSymbol(sym.NULL);
          }
        case 90: break;
        case 6: 
          { return nuevoSymbol(sym.LLAVDER);
          }
        case 91: break;
        case 44: 
          { return nuevoSymbol(sym.STRING);
          }
        case 92: break;
        case 28: 
          { /* Los comentarios se imprimirán */ System.out.println("COMENTARIO: " + yytext());
          }
        case 93: break;
        case 36: 
          { string.append('\"');
          }
        case 94: break;
        case 11: 
          { return nuevoSymbol(sym.PARDER);
          }
        case 95: break;
        case 49: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\"'));
          }
        case 96: break;
        case 21: 
          { return nuevoSymbol(sym.MAYOR);
          }
        case 97: break;
        case 14: 
          { return nuevoSymbol(sym.DOSPUNTOS);
          }
        case 98: break;
        case 30: 
          { return nuevoSymbol(sym.ASIG);
          }
        case 99: break;
        case 42: 
          { return nuevoSymbol(sym.FLOATVAL, new Double(yytext()));
          }
        case 100: break;
        case 63: 
          { return nuevoSymbol(sym.DEFAULT);
          }
        case 101: break;
        case 22: 
          { return nuevoSymbol(sym.MENOR);
          }
        case 102: break;
        case 54: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\r'));
          }
        case 103: break;
        case 17: 
          { return nuevoSymbol(sym.SUMA);
          }
        case 104: break;
        case 51: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\\'));
          }
        case 105: break;
        case 29: 
          { return nuevoSymbol(sym.IF);
          }
        case 106: break;
        case 62: 
          { return nuevoSymbol(sym.FUNCTION);
          }
        case 107: break;
        case 45: 
          { return nuevoSymbol(sym.FOR);
          }
        case 108: break;
        case 31: 
          { return nuevoSymbol(sym.MAYORIGUAL);
          }
        case 109: break;
        case 23: 
          { return nuevoSymbol(sym.IGUAL);
          }
        case 110: break;
        case 37: 
          { string.append('\n');
          }
        case 111: break;
        case 13: 
          { return nuevoSymbol(sym.BRADER);
          }
        case 112: break;
        case 26: 
          { yybegin(YYINITIAL); 
                                   return nuevoSymbol(sym.CADENA, string.toString());
          }
        case 113: break;
        case 53: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\n'));
          }
        case 114: break;
        case 34: 
          { return nuevoSymbol(sym.OR);
          }
        case 115: break;
        case 5: 
          { return nuevoSymbol(sym.LLAVIZQ);
          }
        case 116: break;
        case 68: 
          { return nuevoSymbol(sym.TRUE);
          }
        case 117: break;
        case 8: 
          { yybegin(STRING); string.setLength(0);
          }
        case 118: break;
        case 67: 
          { return nuevoSymbol(sym.WHILE);
          }
        case 119: break;
        case 65: 
          { return nuevoSymbol(sym.BREAK);
          }
        case 120: break;
        case 57: 
          { return nuevoSymbol(sym.VOID);
          }
        case 121: break;
        case 59: 
          { return nuevoSymbol(sym.CASE);
          }
        case 122: break;
        case 64: 
          { return nuevoSymbol(sym.RETURN);
          }
        case 123: break;
        case 60: 
          { return nuevoSymbol(sym.ELSE);
          }
        case 124: break;
        case 10: 
          { return nuevoSymbol(sym.PARIZQ);
          }
        case 125: break;
        case 1: 
          { System.out.println("Caracter Ilegal, '" + yytext() +
                    "' line: " + yyline + ", column: " + yychar);
          }
        case 126: break;
        case 55: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\f'));
          }
        case 127: break;
        case 40: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character(yytext().charAt(0)));
          }
        case 128: break;
        case 3: 
          { return nuevoSymbol(sym.ENTERO, new Integer(yytext()));
          }
        case 129: break;
        case 16: 
          { return nuevoSymbol(sym.MULT);
          }
        case 130: break;
        case 9: 
          { yybegin(sym.CHAR);
          }
        case 131: break;
        case 46: 
          { return nuevoSymbol(sym.FLOAT);
          }
        case 132: break;
        case 25: 
          { string.append( yytext() );
          }
        case 133: break;
        case 2: 
          { return nuevoSymbol(sym.IDENT, yytext());
          }
        case 134: break;
        case 41: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 135: break;
        case 52: 
          { yybegin(YYINITIAL); return nuevoSymbol(sym.CHARVAL, new Character('\b'));
          }
        case 136: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
