
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 18 16:28:40 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 29;
  public static final int BRADER = 22;
  public static final int FUNCTION = 36;
  public static final int MULT = 13;
  public static final int CHAR = 5;
  public static final int ENTERO = 43;
  public static final int FLOATVAL = 45;
  public static final int CASE = 11;
  public static final int RESTA = 15;
  public static final int INT = 2;
  public static final int CHARVAL = 44;
  public static final int PUNTOCOMA = 17;
  public static final int FOR = 7;
  public static final int WRITE = 49;
  public static final int NOIGUAL = 28;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int MENORIGUAL = 25;
  public static final int IGUAL = 27;
  public static final int OR = 41;
  public static final int BOOL = 3;
  public static final int DIV = 16;
  public static final int SUMA = 14;
  public static final int MAIN = 47;
  public static final int IF = 9;
  public static final int MAYORIGUAL = 26;
  public static final int EOF = 0;
  public static final int PARIZQ = 19;
  public static final int RETURN = 38;
  public static final int ASIG = 12;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int CADENA = 39;
  public static final int NULL = 35;
  public static final int MENOR = 23;
  public static final int BRAIZQ = 21;
  public static final int BREAK = 30;
  public static final int IDENT = 31;
  public static final int VOID = 37;
  public static final int SWITCH = 10;
  public static final int MAYOR = 24;
  public static final int ELSE = 32;
  public static final int READ = 48;
  public static final int WHILE = 8;
  public static final int DEFAULT = 46;
  public static final int FLOAT = 4;
  public static final int STRING = 6;
  public static final int FALSE = 34;
  public static final int PARDER = 20;
}

