
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 11 21:31:09 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 32;
  public static final int BRADER = 22;
  public static final int FUNCTION = 40;
  public static final int MULT = 13;
  public static final int CHAR = 5;
  public static final int ENTERO = 48;
  public static final int FLOATVAL = 50;
  public static final int CASE = 11;
  public static final int RESTA = 15;
  public static final int INT = 2;
  public static final int CHARVAL = 49;
  public static final int PUNTOCOMA = 17;
  public static final int LLAVIZQ = 46;
  public static final int FOR = 7;
  public static final int NOIGUAL = 30;
  public static final int AND = 44;
  public static final int MENORIGUAL = 27;
  public static final int IGUAL = 29;
  public static final int OR = 45;
  public static final int BOOL = 3;
  public static final int DIV = 16;
  public static final int SUMA = 14;
  public static final int IF = 9;
  public static final int LLAIZQ = 23;
  public static final int MAYORIGUAL = 28;
  public static final int EOF = 0;
  public static final int PARIZQ = 19;
  public static final int RETURN = 42;
  public static final int ASIG = 12;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMILLA = 31;
  public static final int COMA = 18;
  public static final int CADENA = 43;
  public static final int NULL = 39;
  public static final int MENOR = 25;
  public static final int IDENT = 35;
  public static final int BRAIZQ = 21;
  public static final int BREAK = 34;
  public static final int VOID = 41;
  public static final int SWITCH = 10;
  public static final int MAYOR = 26;
  public static final int LLAVDER = 47;
  public static final int ELSE = 36;
  public static final int PUNTO = 33;
  public static final int WHILE = 8;
  public static final int FLOAT = 4;
  public static final int STRING = 6;
  public static final int LLADER = 24;
  public static final int FALSE = 38;
  public static final int PARDER = 20;
}

